"""Initial schema: users, transactions, preferences, referrals, services, logs

Revision ID: 827683e125de
Revises: 
Create Date: 2025-11-07 00:35:10.280509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827683e125de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=50), nullable=False),
    sa.Column('admin_ip', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_phone', sa.String(length=15), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_action_type'), 'admin_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_logs_admin_username'), 'admin_logs', ['admin_username'], unique=False)
    op.create_index(op.f('ix_admin_logs_id'), 'admin_logs', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('AIRTIME', 'DATA', 'CABLE_TV', 'ELECTRICITY', 'EXAM_PIN', name='servicetype'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('validity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_plan_id'), 'services', ['plan_id'], unique=False)
    op.create_index(op.f('ix_services_type'), 'services', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.Column('virtual_account_number', sa.String(length=20), nullable=True),
    sa.Column('virtual_account_name', sa.String(length=100), nullable=True),
    sa.Column('account_reference', sa.String(length=100), nullable=True),
    sa.Column('default_network', sa.String(length=20), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.String(length=20), nullable=True),
    sa.Column('referral_bonus_claimed', sa.Boolean(), nullable=True),
    sa.Column('nin', sa.String(length=11), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_reference')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('WHATSAPP', 'PAYRANT', 'TOPUPMATE', name='webhooksource'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_event_id'), 'webhook_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_source'), 'webhook_logs', ['source'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referrer_code', sa.String(length=20), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('referee_phone', sa.String(length=15), nullable=False),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('reward_status', sa.String(length=20), nullable=True),
    sa.Column('reward_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_referee_id'), 'referrals', ['referee_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_code'), 'referrals', ['referrer_code'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('AIRTIME', 'DATA', 'ELECTRICITY', 'CABLE_TV', 'EXAM_PIN', 'WALLET_FUNDING', 'WALLET_TRANSFER', 'REFERRAL_BONUS', 'ADMIN_CREDIT', 'ADMIN_DEBIT', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED', name='transactionstatus'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=True),
    sa.Column('new_balance', sa.Float(), nullable=True),
    sa.Column('service_provider', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('recipient_phone', sa.String(length=15), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('meter_number', sa.String(length=50), nullable=True),
    sa.Column('smartcard_number', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_network', sa.String(length=20), nullable=True),
    sa.Column('favorite_numbers', sa.Text(), nullable=True),
    sa.Column('last_airtime_amount', sa.Integer(), nullable=True),
    sa.Column('last_data_plan', sa.String(length=50), nullable=True),
    sa.Column('last_network', sa.String(length=20), nullable=True),
    sa.Column('saved_smartcard', sa.String(length=50), nullable=True),
    sa.Column('saved_cable_provider', sa.String(length=50), nullable=True),
    sa.Column('saved_meter_number', sa.String(length=50), nullable=True),
    sa.Column('saved_meter_type', sa.String(length=20), nullable=True),
    sa.Column('saved_electricity_provider', sa.String(length=50), nullable=True),
    sa.Column('notify_on_transaction', sa.Boolean(), nullable=True),
    sa.Column('notify_on_low_balance', sa.Boolean(), nullable=True),
    sa.Column('low_balance_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referee_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_webhook_logs_source'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_type'), table_name='services')
    op.drop_index(op.f('ix_services_plan_id'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_admin_logs_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_username'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action_type'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
